import { useState, useEffect } from 'react'
import { Sparkles, ChevronRight, RefreshCw } from 'lucide-react'
import { USE_API, api } from '@/lib/api'
import { getUser } from '@/lib/auth'
// DailyBriefingCard uses api.getPortfolioBrief() and api.regeneratePortfolioBrief(),
// which already exist in api.js (added in intel-v7 layer 9).

/**
 * DailyBriefingCard — executive "good morning" AI narrative for the agency dashboard.
 *
 * Reads GET /api/ai/brief (portfolio morning brief) from the ai_briefs table
 * generated by lib/brief.js each morning. Shows the AI-written 2-3 sentence
 * portfolio pulse narrative that the intelligence engine already produces.
 *
 * Agency-only: hidden for role='client'. Silent on error (never breaks dashboard).
 */
export default function DailyBriefingCard() {
  const [brief, setBrief]   = useState(null)
  const [loading, setLoading] = useState(true)
  const [regen, setRegen]   = useState(false)

  const user = USE_API ? getUser() : null
  const isAgency = !user || user.role !== 'client'

  useEffect(() => {
    if (!USE_API || !isAgency) { setLoading(false); return }
    api.getPortfolioBrief()
      .then(r => setBrief(r))
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [isAgency])

  async function handleRegen() {
    if (!USE_API || regen) return
    setRegen(true)
    try {
      const r = await api.regeneratePortfolioBrief()
      if (r) setBrief(r)
    } catch {}
    finally { setRegen(false) }
  }

  if (!isAgency || loading) return null
  if (!brief?.text && !brief?.narrative) return null

  const text = brief.narrative || brief.text || ''
  // Format today as "Monday, June 9"
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric',
  })

  return (
    <div className="bg-gradient-to-r from-brand-500/10 via-violet-500/10 to-sky-500/10 border border-brand-500/20 rounded-2xl px-5 py-4">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3 min-w-0">
          <div className="w-8 h-8 rounded-xl bg-brand-500/20 border border-brand-500/30 flex items-center justify-center shrink-0 mt-0.5">
            <Sparkles className="w-4 h-4 text-brand-400" />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2 mb-1.5">
              <p className="text-[10px] font-black uppercase tracking-wider text-brand-400">
                Agency Brief · {today}
              </p>
            </div>
            <p className="text-sm text-slate-300 leading-relaxed">{text}</p>
            {brief.bullets?.length > 0 && (
              <ul className="mt-2 space-y-0.5">
                {brief.bullets.slice(0, 3).map((b, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-400">
                    <ChevronRight className="w-3 h-3 text-brand-500 shrink-0 mt-0.5" />
                    {b}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
        <button
          onClick={handleRegen}
          disabled={regen}
          title="Regenerate brief"
          className="shrink-0 p-1.5 rounded-lg text-slate-600 hover:text-slate-300 hover:bg-white/5 transition-colors disabled:opacity-40"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${regen ? 'animate-spin' : ''}`} />
        </button>
      </div>
    </div>
  )
}
